### ISSUE TITLE
PPI1 Layout da Área Administrativa: Cadastros - Criação/edição - Campos especiais (G5)

### ISSUE THREAD

**Issue by lfarcaro** [ppi201901/IFSCGAS_PEPPI201901#17]
Desenvolver layout para campos especiais dos formulários de adição/edição de registros, considerando o uso do framework Bootstrap. O layout deverá contemplar:

- Exemplo de editor WYSIWYG.
- Sub-cadastro de fotografias: upload, ordenação e exclusão.

Protótipo:

![CadastroFotografias](https://user-images.githubusercontent.com/48957854/56842910-e8a0f800-6870-11e9-80fc-0c979b6495d0.png)

**Comment by merecedordoo** [comment]
Professor, tem como fazer uma imagem de exemplo? porque eu não estou conseguindo imaginar como seria isso
