### ISSUE TITLE
PPI1 Banco de Dados: Criação do banco de dados (G7)

### ISSUE THREAD

**Issue by lfarcaro** [ppi201901/IFSCGAS_PEPPI201901#18]
Criar o banco de dados do sistema, com base no diagrama ER produzido a partir do processo de análise.

**Comment by lfarcaro** [comment]
Edder,

Tens o script utilizado na criação do banco? Precisaremos colocá-lo no repositório para o pessoal que quiser trabalhar em suas máquinas pessoais poderem criá-lo.

Att.,

Luís

**Comment by EdderGaddini** [comment]
Está correto ?

Em seg, 6 de mai de 2019 às 14:57, Luís Fernando Arcaro <
notifications@github.com> escreveu:
