### ISSUE TITLE
PPI2 Área Administrativa: Cadastro de administradores

### ISSUE THREAD

**Issue by lfarcaro** [ppi201901/IFSCGAS_PEPPI201901#51]
Desenvolver o cadastro de administradores, utilizando o framework CakePHP, que deverá suportar a listagem, criação, edição e exclusão dos administradores cadastrados.

Passos iniciais:
1. Geração automática do modelo utilizando o comando "bake".
1. Geração automática do controlador.
1. Geração automática das templates.
1. Testes e ajustes no cadastro gerado.

Requisitos adicionais:
- Caso um administrador seja criado com um e-mail que já está cadastrado, um alerta deverá ser emitido.
- Remover senha da listagem.

Ajustes:
- Remover ID da listagem
- Remover senha na listagem
- Remover link "View" da listagem
- Remover método "view" do Controller, mas NÃO REMOVER o arquivo view.ctp pois isso gera problemas de tradução no CakePHP
- Apresentar os valores booleanos (Sim/Não) do campo "recebe_contato" utilizando "<?= h($entidade->nomeDoCampo ? __('Yes') : __('No')) ?>".
- Implementar confirmação de senha:
    - Desabilitar "mass assignment" do campo senha.
    - Nos formulários add.ctp e edit.ctp criar dois campos senha ao invés de um, com nomes diferentes do campo no banco
    - No add.ctp ambos os campos devem ser exigidos, enquanto no edit.ctp ambos devem ser opcionais
    - No add do controller verificar se as senhas informadas conferem, senão emitir erro usando Flash e não salvar
    - No edit do controller verificar se as senhas foram informadas: se foram e conferem atribuir a senha e gravar, senão emitir erro usando o Flash e não salvar
    - No edit do controller, se nenhuma senha for informada a senha antiga deve ser mantida

**Comment by mateusFerrando** [comment]
Removido o ID da listagem;
Removido a senha na listagem;
Removido link "View" da listagem;
Removido método "view" do Controller;

**Comment by mateusFerrando** [comment]
implementada validação ao adicionar um adm e já estiver com email na base cadastrado retornar um alerta e nao salva
